### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by basileLeroy** [Drup1k/sass-challenge#1]
# Feedback
Hi Andrej

I was not able to find the exercise in your SASS repository. instead it looks like you made the Holy Grail exercise with SASS, which was not in the instructions. 

Can you let me know what happened? Thank you.

**Comment by Drup1k** [comment]
Hi Basile,

i needed to go to dentist that day and didnt finish with the exercize.
Also ive used the holygrale as just an exampel and tryed to do the exercize with scss.
